version: 5.1.0
variant: default
logo: /images/logo.svg
head:
    favicon: /images/favicon.svg
    manifest:
        name: Kimi's Space
        short_name: 
        start_url: https://kimi.qqviaja.com/
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: KimiCuBao
        twitter_site: https://twitter.com/KimiCuBao
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/kimichen13
footer:
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/kimichen13/kimichen13.github.io
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://github.com/kimichen13/kimichen13.github.io/blob/main/LICENSE
search:
    type: insight
comment:
    type: disqus
    shortname: kimichen
donates:
    -
        type: alipay
        qrcode: 'https://qr.alipay.com/fkx15373carord7ustszq3f'
    -
        type: paypal
        business: kimichen13@gmail.com
        currency_code: USD
    -
        type: wechat
        qrcode: 'wxp://f2f1_lz2AN8a7xPRTaYRHSZKyjsFwWp9BM8qzlKkW0M7zIT1xANZn5Z8bF-DxojB82I5'
share:
    type: sharethis
    install_url: https://platform-api.sharethis.com/js/sharethis.js#property=6217916a33ac230019282e03&product=inline-share-buttons
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: Kimi Chen
        author_title: 
        location: Shanghai, China
        avatar: /images/avatar.svg
        avatar_rounded: false
        gravatar: 
        follow_link: https://github.com/kimichen13
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/kimichen13
            Twitter:
                icon: fab fa-twitter
                url: https://twitter.com/KimiCuBao
            RSS:
                icon: fas fa-rss
                url: /
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: left
        type: links
        links:
            Hexo: https://hexo.io
            Bulma: https://bulma.io
    -
        position: left
        type: categories
    -
        position: right
        type: recent_posts
    -
        position: right
        type: archives
    -
        position: right
        type: tags
    -
        position: left
        type: adsense
        client_id: ca-pub-8007050323069842
        slot_id: '5599659500'
    -
        position: left
        type: followit
        description: 
        action_url: ''
        verification_code: ''
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: UA-131370295-1
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
